version: 2.1

orbs:
  docker: ledger/docker@dev:INFRA-677_custom_docker_repos_name-1023f083923033d00299f1352bdaf8a87dd75470
  #docker: ledger/docker@volatile

workflows:
  build_test_and_publish:
    jobs:
      - docker/build_image:
          filters:
            tags:
              only: /.*/
      - docker/test_image:
          requires:
            - docker/build_image
          filters:
            tags:
              only: /.*/
      - docker/publish_image:
          requires:
            - docker/test_image
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
